# Generated by Django 4.1.1 on 2023-01-29 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_j", "0007_schedule_cron_expr_schedule_is_recurring_and_more"),
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleToPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="blog.post"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="calendar_j.schedule",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="schedules",
            field=models.ManyToManyField(
                blank=True, through="blog.ScheduleToPost", to="calendar_j.schedule"
            ),
        ),
    ]
