# Generated by Django 4.1.1 on 2023-02-03 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_j", "0007_schedule_cron_expr_schedule_is_recurring_and_more"),
        ("blog", "0003_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="cid",
        ),
        migrations.RemoveField(
            model_name="post",
            name="pid",
        ),
        migrations.AddField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=2,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=3,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="comment",
            table="tb_comment",
        ),
        migrations.AlterModelTable(
            name="post",
            table="tb_post",
        ),
        migrations.CreateModel(
            name="ScheduleToPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.post"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_j.schedule",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="schedules",
            field=models.ManyToManyField(
                blank=True, through="blog.ScheduleToPost", to="calendar_j.schedule"
            ),
        ),
    ]
