version: "3"

services:
  interface:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_INTERFACE}:${IMAGE_TAG}
    environment:
      SITE: PROD
    ports:
      - 8000:8000

  nginx:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY_NGINX}:${IMAGE_TAG}
    depends_on:
      - interface
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  dear_j:
