# Generated by Django 4.1.1 on 2023-01-17 20:05

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Presence"),
                            (2, "Absence"),
                            (3, "Hold"),
                            (4, "Unanswered"),
                        ],
                        default=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "participant",
                "verbose_name_plural": "participants",
                "db_table": "tb_participant",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "protection_level",
                    models.IntegerField(choices=[(1, "Open"), (2, "Follower"), (3, "Closed")], default=1),
                ),
                ("show_content", models.BooleanField(blank=True, default=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("description", models.TextField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_opened", models.BooleanField(blank=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(through="calendar_j.Participant", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "schedule",
                "verbose_name_plural": "schedules",
                "db_table": "tb_schedule",
            },
        ),
        migrations.AddField(
            model_name="participant",
            name="schedule",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="calendar_j.schedule"),
        ),
    ]
