# Generated by Django 4.1.1 on 2023-01-01 08:00

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendar_j", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="participant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="participant",
            name="schedule",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="calendar_j.schedule"),
        ),
    ]
