# Generated by Django 4.1.1 on 2023-01-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_j", "0002_alter_participant_participant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="url",
        ),
    ]
