# Generated by Django 4.1.1 on 2023-01-03 06:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_j", "0003_remove_schedule_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
