# Generated by Django 4.1.1 on 2023-01-04 14:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_j", "0004_participant_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
