# Generated by Django 4.1.1 on 2023-01-21 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_j", "0005_alter_schedule_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="is_opened",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_recurring",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="schedule",
            name="show_content",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="protection_level",
            field=models.IntegerField(
                choices=[(1, "Open"), (2, "Follower"), (3, "Closed")], default=1
            ),
        ),
        migrations.CreateModel(
            name="RecurringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cron",
                    models.IntegerField(
                        choices=[(1, "Day"), (2, "Week"), (3, "Month"), (4, "Year")]
                    ),
                ),
                ("end_date", models.DateField()),
                (
                    "schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_rule",
                        to="calendar_j.schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "recurring_rule",
                "verbose_name_plural": "recurring_rules",
                "db_table": "tb_recurring_rule",
            },
        ),
        migrations.CreateModel(
            name="RecurringRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_record",
                        to="calendar_j.schedule",
                    ),
                ),
            ],
        ),
    ]
