# Generated by Django 4.1.1 on 2023-01-15 20:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calendar_j",
            "0006_schedule_show_content_alter_schedule_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_opened",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
