# Generated by Django 4.1.1 on 2023-01-24 13:12

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_j", "0006_schedule_is_opened_schedule_show_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "schedule_group",
                "verbose_name_plural": "schedule_groups",
                "db_table": "tb_schedule_group",
            },
        ),
        migrations.AddField(
            model_name="schedule",
            name="cron_expr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurring_end_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="is_opened",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="show_content",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ScheduleToGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_j.schedulegroup",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendar_j.schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "schedule_to_group",
                "verbose_name_plural": "schedules_to_groups",
                "db_table": "tb_schedule_to_group",
            },
        ),
        migrations.AddField(
            model_name="schedule",
            name="schedule_groups",
            field=models.ManyToManyField(through="calendar_j.ScheduleToGroup", to="calendar_j.schedulegroup"),
        ),
    ]
