# Generated by Django 4.1.1 on 2023-01-26 10:48

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("calendar_j", "0006_schedule_is_opened_schedule_show_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="cron_expr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurring_end_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="is_opened",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="show_content",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="RecurringScheduleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("is_opened", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_schedule_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recurring_schedule_group",
                "verbose_name_plural": "recurring_schedule_groups",
                "db_table": "tb_recurring_schedule_group",
            },
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurring_schedule_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedules",
                to="calendar_j.recurringschedulegroup",
            ),
        ),
    ]
