# Generated by Django 4.1.1 on 2023-01-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_j", "0006_schedule_is_opened_schedule_is_recurring_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringrule",
            name="cronjob",
        ),
        migrations.AddField(
            model_name="recurringrule",
            name="cron",
            field=models.IntegerField(
                choices=[(1, "Day"), (2, "Week"), (3, "Month"), (4, "Year")], default=4
            ),
            preserve_default=False,
        ),
    ]
