# Generated by Django 4.1.1 on 2023-01-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_j", "0006_schedule_is_opened_schedule_is_recurring_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringrule",
            name="schedule",
        ),
        migrations.AddField(
            model_name="schedule",
            name="recurring_rule",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule",
                to="calendar_j.recurringrule",
            ),
        ),
    ]
