# Generated by Django 4.1.1 on 2023-01-24 23:32

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_j", "0007_schedulegroup_schedule_cron_expr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="schedule",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="calendar_j.schedule"),
        ),
    ]
