# Generated by Django 4.1.1 on 2023-01-05 14:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="is_opened",
            field=models.BooleanField(default=True),
        ),
    ]
