# Generated by Django 4.1.1 on 2023-01-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_network_is_opened"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="network",
            name="is_opened",
        ),
    ]
