# Generated by Django 4.1.1 on 2023-01-29 17:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_remove_network_is_opened"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="approved",
            field=models.BooleanField(null=True),
        ),
    ]
