# Generated by Django 4.1.1 on 2022-12-26 14:11

import datetime

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_remove_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(default=datetime.date(2022, 12, 26)),
            preserve_default=False,
        ),
    ]
