# Generated by Django 4.1.1 on 2022-12-27 03:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_birthday"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="username", max_length=30),
            preserve_default=False,
        ),
    ]
