# Generated by Django 4.1.1 on 2023-01-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(null=True),
        ),
    ]
