# Generated by Django 4.1.1 on 2023-01-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_rename_birthday_user_birthdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="date_joined",
            new_name="created_at",
        ),
    ]
