# Generated by Django 4.1.1 on 2023-01-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_birthday"),
        ("user", "0006_rename_date_joined_user_created_at"),
    ]

    operations = []
