# Generated by Django 4.1.1 on 2023-01-29 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_user_birthday_user_birthyear"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="https://dear-j-blog.s3.ap-northeast-2.amazonaws.com/user/user.png",
                upload_to="user",
            ),
        ),
    ]
