# Generated by Django 4.1.1 on 2023-01-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="https://dear-j-blog.s3.ap-northeast-2.amazonaws.com/user/user.png",
                null=True,
                upload_to="user",
            ),
        ),
    ]
